"""add tiles to boards

Revision ID: ceab352ff1b2
Revises: 97c54707b681
Create Date: 2021-07-06 11:56:37.461058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceab352ff1b2'
down_revision = '97c54707b681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('initialTiles', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'initialTiles')
    # ### end Alembic commands ###
