"""fix consistent casing

Revision ID: 31b22b6caa0a
Revises: ceab352ff1b2
Create Date: 2021-07-09 17:20:06.474744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b22b6caa0a'
down_revision = 'ceab352ff1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('initial_board_setup', sa.String(length=255), nullable=False))
    op.add_column('boards', sa.Column('initial_tiles', sa.String(), nullable=False))
    op.drop_constraint('boards_initialBoardSetup_key', 'boards', type_='unique')
    op.create_unique_constraint(None, 'boards', ['initial_board_setup'])
    op.drop_column('boards', 'initialTiles')
    op.drop_column('boards', 'initialBoardSetup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('initialBoardSetup', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('initialTiles', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'boards', type_='unique')
    op.create_unique_constraint('boards_initialBoardSetup_key', 'boards', ['initialBoardSetup'])
    op.drop_column('boards', 'initial_tiles')
    op.drop_column('boards', 'initial_board_setup')
    # ### end Alembic commands ###
