"""new

Revision ID: 97c54707b681
Revises: 9dca114612c8
Create Date: 2021-07-05 18:32:13.923507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c54707b681'
down_revision = '9dca114612c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_sessions', sa.Column('tiles', sa.String(), nullable=False))
    op.add_column('users', sa.Column('current_session_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_session_id')
    op.drop_column('play_sessions', 'tiles')
    # ### end Alembic commands ###
